directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
appId: net.latestday
productName: WorkBench
mac:
  icon: ./public/icon.ico
electronVersion: 11.3.0
